
CREATE TABLE ORDERS (
    BLOOD_STOCK_ID  VARCHAR(20),
    HOSPITAL_ID     VARCHAR(20),
    ORDER_DATE      DATE NOT NULL,
    ORDER_QUANTITY  DECIMAL(5, 2),
    PRIMARY KEY (BLOOD_STOCK_ID, HOSPITAL_ID, ORDER_DATE),
    FOREIGN KEY (BLOOD_STOCK_ID) REFERENCES BLOOD_BANK(BLOOD_STOCK_ID),
    FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(HOSPITAL_ID)
);

USE DB;
SHOW TABLES;
select *from donor;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BLOOD_BANK;
CREATE TABLE BLOOD_BANK (
    BLOOD_STOCK_ID        VARCHAR(20) PRIMARY KEY,
    BLOOD_ID              VARCHAR(20) NOT NULL,  -- remove UNIQUE to allow multiple stocks of same blood type
    AVAILABLE_BLOOD_GROUP VARCHAR(5) NOT NULL,
    QUANTITY              DECIMAL(5,2) NOT NULL,
    EXPIRY_DATE           DATE NOT NULL,
    COLLECTION_DATE       DATE,
    
    FOREIGN KEY (BLOOD_ID) REFERENCES BLOOD(BLOOD_ID)
);
SET FOREIGN_KEY_CHECKS = 1;
use db;
show tables;
SELECT * FROM DONOR;
SELECT 
    AVAILABLE_BLOOD_GROUP AS BLOOD_GROUP, 
    SUM(QUANTITY) AS TOTAL_UNITS
FROM BLOOD_BANK
GROUP BY AVAILABLE_BLOOD_GROUP;
SELECT 
    B.BLOOD_ID,
    B.BLOOD_GROUP,
    B.DONATION_DATE,
    D.DONOR_NAME
FROM BLOOD B
JOIN DONOR D ON B.DONOR_ID = D.DONOR_ID
ORDER BY B.DONATION_DATE DESC
LIMIT 5;
SELECT 
    P.PATIENT_ID,
    P.PATIENT_NAME,
    P.REQUESTED_BLOOD_GROUP,
    H.HOSPITAL_NAME
FROM PATIENT P
LEFT JOIN HOSPITAL H ON P.HOSPITAL_ID = H.HOSPITAL_ID;
SELECT COUNT(*) AS total_hospitals
FROM HOSPITAL;
SELECT COUNT(*) AS total_orders
FROM ORDERS;
SELECT BLOOD_STOCK_ID, AVAILABLE_BLOOD_GROUP, EXPIRY_DATE
FROM BLOOD_BANK
WHERE EXPIRY_DATE <= CURDATE() + INTERVAL 1 year;
SELECT DISTINCT H.HOSPITAL_NAME
FROM ORDERS O
JOIN BLOOD_BANK BB ON O.BLOOD_STOCK_ID = BB.BLOOD_STOCK_ID
JOIN HOSPITAL H ON O.HOSPITAL_ID = H.HOSPITAL_ID
WHERE BB.AVAILABLE_BLOOD_GROUP = 'A+';
UPDATE BLOOD
SET QUANTITY_OF_BLOOD = 0.75
WHERE BLOOD_ID = 'B001';
SELECT 
    B.BLOOD_ID, 
    B.BLOOD_GROUP, 
    B.DONATION_DATE, 
    B.QUANTITY_OF_BLOOD, 
    D.DONOR_NAME, 
    D.DONOR_CONTACT
FROM BLOOD B
JOIN DONOR D ON B.DONOR_ID = D.DONOR_ID
ORDER BY B.DONATION_DATE DESC;
SELECT 
    D.DONOR_NAME,
    B.BLOOD_GROUP,
    B.DONATION_DATE
FROM DONOR D
JOIN BLOOD B ON D.DONOR_ID = B.DONOR_ID
WHERE D.DONOR_NAME LIKE '%ra%';
SELECT 
    P.PATIENT_ID,
    P.PATIENT_NAME,
    P.REQUESTED_BLOOD_GROUP,
    H.HOSPITAL_NAME,
    H.HOSPITAL_ADDRESS
FROM PATIENT P
JOIN HOSPITAL H ON P.HOSPITAL_ID = H.HOSPITAL_ID;
SELECT 
    B.BLOOD_ID,
    B.BLOOD_GROUP,
    B.DONATION_DATE,
    BB.BLOOD_STOCK_ID,
    BB.AVAILABLE_BLOOD_GROUP,
    BB.QUANTITY,
    BB.EXPIRY_DATE
FROM BLOOD B
JOIN BLOOD_BANK BB ON B.BLOOD_ID = BB.BLOOD_ID;
SELECT 
    BB.BLOOD_STOCK_ID,
    B.BLOOD_GROUP,
    BB.QUANTITY,
    BB.EXPIRY_DATE
FROM BLOOD_BANK BB
JOIN BLOOD B ON B.BLOOD_ID = BB.BLOOD_ID
WHERE B.BLOOD_GROUP LIKE 'A%';
SELECT 
    D.DONOR_NAME,
    BB.AVAILABLE_BLOOD_GROUP,
    BB.EXPIRY_DATE
FROM DONOR D
JOIN BLOOD B ON D.DONOR_ID = B.DONOR_ID
JOIN BLOOD_BANK BB ON B.BLOOD_ID = BB.BLOOD_ID
WHERE D.DONOR_NAME LIKE '%vi%';
SELECT 
    D.DONOR_NAME,
    D.DONOR_CONTACT,
    B.BLOOD_GROUP,
    BB.BLOOD_STOCK_ID,
    O.ORDER_DATE,
    O.ORDER_QUANTITY,
    H.HOSPITAL_NAME,
    P.PATIENT_NAME,
    P.REQUESTED_BLOOD_GROUP
FROM DONOR D
JOIN BLOOD B ON D.DONOR_ID = B.DONOR_ID
JOIN BLOOD_BANK BB ON B.BLOOD_ID = BB.BLOOD_ID
JOIN ORDERS O ON BB.BLOOD_STOCK_ID = O.BLOOD_STOCK_ID
JOIN HOSPITAL H ON O.HOSPITAL_ID = H.HOSPITAL_ID
JOIN PATIENT P ON H.HOSPITAL_ID = P.HOSPITAL_ID
WHERE D.DONOR_NAME LIKE '%a%';
SELECT 
    D.DONOR_NAME,
    COUNT(B.BLOOD_ID) AS Total_Donations
FROM DONOR D
JOIN BLOOD B ON D.DONOR_ID = B.DONOR_ID
GROUP BY D.DONOR_NAME
HAVING COUNT(B.BLOOD_ID) > 1;
SELECT 
    D.DONOR_NAME,
    MAX(B.DONATION_DATE) AS Last_Donation
FROM DONOR D
JOIN BLOOD B ON D.DONOR_ID = B.DONOR_ID
GROUP BY D.DONOR_NAME;
SELECT 
    AVAILABLE_BLOOD_GROUP,
    SUM(QUANTITY) AS Total_Units
FROM BLOOD_BANK
GROUP BY AVAILABLE_BLOOD_GROUP
ORDER BY Total_Units DESC;
SELECT 
    BLOOD_STOCK_ID,
    AVAILABLE_BLOOD_GROUP,
    EXPIRY_DATE
FROM BLOOD_BANK
WHERE EXPIRY_DATE BETWEEN CURDATE() AND CURDATE() + INTERVAL 30 DAY;
SELECT 
    D.DONOR_NAME,
    B.BLOOD_GROUP,
    BB.EXPIRY_DATE
FROM DONOR D
JOIN BLOOD B ON D.DONOR_ID = B.DONOR_ID
JOIN BLOOD_BANK BB ON B.BLOOD_ID = BB.BLOOD_ID
WHERE B.BLOOD_GROUP LIKE 'O%';
SELECT 
    H.HOSPITAL_NAME,
    COUNT(O.BLOOD_STOCK_ID) AS Total_Orders
FROM HOSPITAL H
JOIN ORDERS O ON H.HOSPITAL_ID = O.HOSPITAL_ID
GROUP BY H.HOSPITAL_NAME
HAVING COUNT(O.BLOOD_STOCK_ID) > 3;


























